### PR TITLE
chore: update mainnet config

### PR DESCRIPTION
**Pull request by nduchak**

### CODE REVIEW

**Comment by 0xartem** [comment]
@nduchak what issue this codes fixes?

**Comment by nduchak** [comment]
> @nduchak what issue this codes fixes?

disable triggers by default
add proper mainnet config

**Comment by 0xartem** [comment]
> > @nduchak what issue this codes fixes?
> 
> disable triggers by default
> add proper mainnet config

@nduchak do we need it in the mainnet release? I though Juraj had fixed it already.

**Comment by nduchak** [comment]
> > > @nduchak what issue this codes fixes?
> > 
> > 
> > disable triggers by default
> > add proper mainnet config
> 
> @nduchak do we need it in the mainnet release? I though Juraj had fixed it already.

Ahh... You are right. This fix is not included in develop, that's why I miss it

**Comment by nduchak** [comment]
I will close this one and create another just to disable triggers (this need because we need to sync staging with develop)

**Comment by 0xartem** [comment]
> I will close this one and create another just to disable triggers (this need because we need to sync staging with develop)

okay

**Pull request closed without merging**
