### PR TITLE
feat(config): adds storage to mainnet

### PR DESCRIPTION
**Pull request by jurajpiar**
Adds missing storage config for mainnet deployment

### CODE REVIEW

**Review by 0xartem — APPROVED** [review]

**Comment by nduchak** [comment]
Just thinking should we increase confirmations to 8? As we had 8 on testnet

**Comment by 0xartem** [comment]
> Just thinking should we increase confirmations to 8? As we had 8 on testnet

My opinion is that 4 is more than enough. Unless a transaction is  a million dollars or smth it doesn't make sense to wait until 6 confirmations for bitcoin network for example. I suppose the consensus is the same here so we should be fine. Actually even 3 should be fine. In Ethereum dApps they even wait for just 1 to improve UX (I think so) which works fine at scale with a lot of real users.

**Comment by nduchak** [comment]
Agree, but in our case it was done only because of lot of reorgs, and this confirmation range save us from reorg out of range which will require manual resolution

**Review by nduchak — APPROVED** [review]

**Comment by 0xartem** [comment]
> Agree, but in our case it was done only because of lot of reorgs, and this confirmation range save us from reorg out of range which will require manual resolution

Ok, I didn't know that. Other services use 4 as well. Let's use the same number across all the services. Whatever it will be.

**Pull request merged**
