### PR TITLE
fix(notifier): adds notificationsBalance, fix addr

### PR DESCRIPTION
**Pull request by jurajpiar**
Adds missing notificationsBalance field in the subscription model
Also fixes notifier contract addresses for ganache

### CODE REVIEW

**Comment by nduchak** [comment]
All good, just need to add this field in migration file

**Comment by jurajpiar** [comment]
> All good, just need to add this field in migration file

It's here
https://github.com/rsksmart/rif-marketplace-cache/pull/633/files#diff-ccf35de765e23ca21519b8651936f8242792c7e7f9d85107997adfeeb8796994R180-R184

**Review by nduchak — DISMISSED** [review]
Sorry, miss that one)

**Comment by jurajpiar** [comment]
❗️DO NOT MERGE, please. It should be all done, just need to wait for [the notifier service](https://github.com/rsksmart/rif-notifier/pulls) to adapt its currency field from token name to token address before merging. This should be already under way, right @vjgene / @artem-brazhnikov?

**Review by nduchak — APPROVED** [review]
Nice job!

**Comment by 0xartem** [comment]
> DO NOT MERGE, please. It should be all done, just need to wait for [the notifier service](https://github.com/rsksmart/rif-notifier/pulls) to adapt its currency field from token name to token address before merging. This should be already under way, right @vjgene / @artem-brazhnikov?

yes, it's now merged in develop of the rif-notifier @jurajpiar

**Pull request merged**
